### ISSUE TITLE
 Create release for docker file and helm charts

### ISSUE THREAD

**Issue by gpelouze** [NaaVRE/NaaVRE-containerizer-service#6]
Look at https://github.com/QCDIS/dajs-api/blob/main/.github/workflows/build-helm.yaml

**Comment by skoulouzis** [comment]
Jobs seem to be stuck waiting for runners: https://github.com/NaaVRE/NaaVRE-containerizer-service/actions/runs/11820297145

**Comment by gpelouze** [comment]
The runners are fixed by https://github.com/NaaVRE/NaaVRE-containerizer-service/pull/14.

Created a new release to test build: https://github.com/NaaVRE/NaaVRE-containerizer-service/releases/tag/v0.1.1

`call-pytest` fails on self-hosted runners: https://github.com/NaaVRE/NaaVRE-containerizer-service/actions/runs/12142238401/attempts/1 but not on GitHub runners: https://github.com/NaaVRE/NaaVRE-containerizer-service/actions/runs/12142238401/attempts/2

**Comment by gpelouze** [comment]
- [X] tests on GitHub runners
- [ ] tests on self-hosted runners: needs work
- [X] build docker and helm: configured ghcr.io and updated container name
- [X] push to ghcr.io: enabled Actions > General > Workflow permissions > Read and write permissions in NaaVRE org and current repo
- [X] removed `v0.1.1-testX` test releases and create a new [v0.1.1 release](https://github.com/NaaVRE/NaaVRE-containerizer-service/releases/tag/v0.1.1)
